config/routes.rb
Tweet2notes::Application.routes.draw do
  get "parameter/input"

  post "parameter/register" => "parameter#register"

  get "create_note/create"

  get "login/twCallback"

  get "login/enCallback"

  get "login/twLogout"

  get "login/enLogout"

  get "contents/index"
  root :to => "contents#index"

  match 'auth/twitter/callback' => 'login#twCallback'
  match 'auth/evernote/callback' => 'login#enCallback'

  get 'auth/twitter'
  get 'auth/evernote'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :en_token, :notebook, :tags, :tw_secret, :tw_token, :tweeting, :updated_at
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def index
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def twCallback
    session[:twtoken] = request.env['omniauth.auth']['credentials']['token']
    session[:twsecret] = request.env['omniauth.auth']['credentials']['secret']

    redirect_to root_url, :notice => "Twitter signed in!"
  end

  def enCallback
    session[:entoken] = request.env['omniauth.auth']['credentials']['token']

    redirect_to root_url, :notice => "Evernote signed in!"
  end

  def twLogout
    session[:twtoken] = nil
    session[:twsecret] = nil

    redirect_to root_url, :notice => "Twitter signed out!"
  end

  def enLogout
    session[:entoken] = nil

    redirect_to root_url, :notice => "Evernote signed out!"
  end
end

app/controllers/parameter_controller.rb
class ParameterController < ApplicationController
  def input

    if (session[:twtoken] == nil) or 
       (session[:twsecret] == nil) or
       (session[:entoken] == nil) then

      redirect_to root_url, :notice => "please login both!!"

    end

  end

  def register
    
    User.create(:tw_token => session[:twtoken], 
                :tw_secret => session[:twsecret],
                :en_token => session[:entoken],
                :notebook => params[:notebook_name],
                :tags => params[:tag_names],
                :tweeting => params[:tweet],
                :updated_at => Time.now)
                
    redirect_to root_url, :notice => 'your token is registered!!'

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/parameter_helper.rb
module ParameterHelper
end

app/views/contents/index.html.erb
<div class="hero-unit">
  <h1>Get Your Tweets!</h1>

  <p><small>
    tweet2notesは每日午前0時(JST)にあなたのTwitterアカウントのツイートを読み込み、その日一日のツイートをすべてまとめてEvernoteの新規ノートとして保存します。<br />
    Twitter, Evernoteの両方での認証の後、登録してください。<br />
    登録を解除する場合は、Twitter, Evernoteそれぞれの設定よりアプリ連携を解除してください。
  </small></p>
  
  <p>
    <% if session[:twtoken] == nil then %>
      <%= link_to 'Twitter Authorize &raquo;'.html_safe, auth_twitter_path, :class => 'btn btn-info' %>
    <% else %>
      <%= link_to 'Twitter Logout', login_twLogout_path, :class => 'btn btn-info' %>
    <% end %>
  </p>
  
  <p>
    <% if session[:entoken] == nil then %>
      <%= link_to 'Evernote Authorize &raquo;'.html_safe, auth_evernote_path, :class => 'btn btn-success' %>
    <% else %>
      <%= link_to 'Evernote Logout', login_enLogout_path, :class => 'btn btn-success' %>
    <% end %>
  </p>
  
  <p>
    <% if session[:twtoken] != nil and session[:entoken] != nil then %>
      <%= link_to 'NextStep &raquo;'.html_safe, parameter_input_path, :class => 'btn btn-primary btn-large' %>
    <% else %>
      <%= link_to 'NextStep &raquo;'.html_safe, '#', :class => 'btn btn-primary btn-large disabled' %>
    <% end %>
  </p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "tweet2notes" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

      </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">tweet2notes</a>
          
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <%= bootstrap_flash %>
        <%= yield %>
      </div><!--/row-->

      <footer>
        <p>Copyright(C) 2013 Rintaro Okamura - <a href="http://twitter.com/gh_rinx">@gh_rinx</a> All rights reserved.</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/login/enCallback.html.erb
<h1>Login#enCallback</h1>
<p>Find me in app/views/login/enCallback.html.erb</p>

app/views/login/enLogout.html.erb
<h1>Login#enLogout</h1>
<p>Find me in app/views/login/enLogout.html.erb</p>

app/views/login/twCallback.html.erb
<h1>Login#twCallback</h1>
<p>Find me in app/views/login/twCallback.html.erb</p>

app/views/login/twLogout.html.erb
<h1>Login#twLogout</h1>
<p>Find me in app/views/login/twLogout.html.erb</p>

app/views/parameter/input.html.erb
<div class="hero-unit">

  <h1>Set Parameters</h1>

  <%= form_tag('/parameter/register', :method => 'post') do %>
    <label>notebook name</label>
    <%= text_field_tag 'notebook_name' %>
    <small class="help-block">保存先のノートブックを指定してください。</small>

    <label>tags</label>
    <%= text_field_tag 'tag_names' %>
    <small class="help-block">ノートに付けるタグを指定してください。(","で区切って複数指定できます。)</small>

    <label>tweet</label>
    <%= check_box_tag 'tweet' %><small>ノート作成時に通知をする</small>
    <small class="help-block">ノートを作成したことをツイートにより通知します。</small>

    <%= link_to '&laquo; back'.html_safe, root_path, :class => 'btn' %>
    <%= submit_tag 'register &raquo;'.html_safe, :class => 'btn btn-primary' %>

  <% end %>

</div>

app/views/parameter/register.html.erb
<h1>Parameter#register</h1>
<p>Find me in app/views/parameter/register.html.erb</p>